### ISSUE TITLE
Unable to start test system 'slim': java.io.IOException: Cannot run program “java”: error=2, No such file or directory

### ISSUE THREAD

**Issue by MOZAKATAK** [markfink/dbslim#1]
I am using FitNesse slim for database testing, using this as my base project: https://github.com/markfink/dbslim

I have built the dbslim .jar using maven in eclipse and copied it onto a UNIX servers lib folder (at /var/tmp/fitnesse/lib) which already contains all the needed dependencies. I run the #!/bin/ksh /var/java/1.7.0_51/bin/java -jar lib/fitnesse-standalone.jar & command from /var/tmp, starting FitNesse on port 80. I navigate to MyServer:80 on my browser and try to run a test page. I'm greeted with

Unable to start test system 'slim': java.io.IOException: Cannot run program "java": error=2, No such file or directory when I have fixture code and when I have none I receive

Could not complete testing: java.io.IOException: Cannot run program "java": error=2, No such file or directory

Can someone explain how FitNesse cannot find the java version to run?

**Comment by markfink** [comment]
difficult to say based on the data you give. My guess would be that your JAVA_HOME environment variable is not set and your java binary is not contained in your path variable. So it appears this has nothing to do with dbslim. Try to run fitnesse without any plugins.
